### ISSUE TITLE
雲端Danger.form似乎無法正常下載

### ISSUE THREAD

**Issue by G-Sea** [sudoskys/Openaibot#44]
python main.py 

_初始化失败 -> https://raw.githubusercontent.com/fwwdn/sensitive-stop-words/master/%E6%94%BF%E6%B2%BB%E7%B1%BB.txt
初始化失败 -> https://raw.githubusercontent.com/TelechaBot/AntiSpam/main/Danger.txt
初始化 -> Danger.form
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from App.Controller import BotRunner
  File "/home/tk/文档/Openaibot-main/App/Controller.py", line 16, in <module>
    from App import Event
  File "/home/tk/文档/Openaibot-main/App/Event.py", line 40, in <module>
    ContentDfa = DFA(path="./Data/Danger.form")
  File "/home/tk/文档/Openaibot-main/utils/Detect.py", line 60, in __init__
    self.get_words()
  File "/home/tk/文档/Openaibot-main/utils/Detect.py", line 64, in get_words
    with open(self.path, 'r', encoding='utf-8-sig') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Data/Danger.form'_

**Comment by sudoskys** [comment]
方案
1. 可以手动新建一个 Danger.form,里面放上禁用词，一行一个，至少要有一个。
2. 检查网络设置，配置代理或者其他。

**Comment by G-Sea** [comment]
謝謝，已經解決

**Comment by sudoskys** [comment]
> 謝謝，已經解決

记得及时同步更新，刚刚修复bug
