### ISSUE TITLE
在更新到最新版本后，多API管理出现了问题

### ISSUE THREAD

**Issue by sider2vf** [sudoskys/Openaibot#59]
使用 `curl -LO https://raw.githubusercontent.com/sudoskys/Openaibot/main/setup.sh && sh setup.sh` 执行更新并保留原配置后，再次启动机器人，已有的 API key 是正常的，但如果我执行 `/add_api_key` 以后，再使用 `/see_api_key` 查看 API key 列表，就会发现只剩下刚刚添加的 API key 了，查看 `run.log` 无报错，只有执行成功的日志，检查了 `Openaibot\Config\api_keys.json` ，也只有刚刚添加的 API key ，初步怀疑是 [Event.py](https://github.com/sudoskys/Openaibot/blob/main/App/Event.py) 的问题

**Comment by sider2vf** [comment]
aaa03eae3cf64e41ed0dab3fc95fcd7804c9aa67 应该是这个提交

**Comment by sudoskys** [comment]
可能是这样的，我看看

**Comment by sudoskys** [comment]
预测是 pop key 的问题？我测试一下。

**Comment by sudoskys** [comment]
尝试修复了，可以测试一下

**Comment by sider2vf** [comment]
它现在不能运行了，以下是错误日志：

```
Traceback (most recent call last):
  File "/root/Openaibot/main.py", line 7, in <module>
    from App.Controller import BotRunner
  File "/root/Openaibot/App/Controller.py", line 16, in <module>
    from App import Event
  File "/root/Openaibot/App/Event.py", line 14, in <module>
    from utils.Chat import Utils, Usage, rqParser, GroupManger, UserManger, Header
  File "/root/Openaibot/utils/Chat.py", line 9, in <module>
    from utils.Data import DefaultData, DataWorker, DictUpdate, Usage_Data
  File "/root/Openaibot/utils/Data.py", line 54
    def add_key(key: str,filePath：str="./Config/api_keys.json"):
                                 ^
SyntaxError: invalid character '：' (U+FF1A)
```
